"""initial_schema

Revision ID: b1e323f11b36
Revises: 
Create Date: 2024-12-13 23:08:40.644173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1e323f11b36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seller_profiles_id', table_name='seller_profiles')
    op.drop_table('seller_profiles')
    op.drop_index('ix_buyer_profiles_id', table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('max_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='buyer_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='buyer_profiles_pkey')
    )
    op.create_index('ix_buyer_profiles_id', 'buyer_profiles', ['id'], unique=False)
    op.create_table('seller_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verification_status', postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_listings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='seller_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='seller_profiles_pkey')
    )
    op.create_index('ix_seller_profiles_id', 'seller_profiles', ['id'], unique=False)
    # ### end Alembic commands ###
