"""add_property_photos

Revision ID: bb0a33196fca
Revises: 
Create Date: 2024-12-13 07:24:19.412432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0a33196fca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('photos', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('properties', sa.Column('main_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'main_photo')
    op.drop_column('properties', 'photos')
    # ### end Alembic commands ###
